/**
 *
 * @author matthew.towles
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortOrderButtons = new javax.swing.ButtonGroup();
        numTypeButtons = new javax.swing.ButtonGroup();
        unsortedLabel = new javax.swing.JLabel();
        sortedLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        unsortedField = new javax.swing.JTextField();
        sortedField = new javax.swing.JTextField();
        numTypePanel = new javax.swing.JPanel();
        integerButton = new javax.swing.JRadioButton();
        fractionButton = new javax.swing.JRadioButton();
        sortOrderPanel = new javax.swing.JPanel();
        descendingButton = new javax.swing.JRadioButton();
        ascendingButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unsortedLabel.setText("Original List");

        sortedLabel.setText("Sorted List");

        submitButton.setText("Perform Sort");

        sortedField.setEditable(false);

        numTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Numeric Type"));

        numTypeButtons.add(integerButton);
        integerButton.setSelected(true);
        integerButton.setText("Integer");

        numTypeButtons.add(fractionButton);
        fractionButton.setText("Fraction");

        javax.swing.GroupLayout numTypePanelLayout = new javax.swing.GroupLayout(numTypePanel);
        numTypePanel.setLayout(numTypePanelLayout);
        numTypePanelLayout.setHorizontalGroup(
            numTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fractionButton)
                    .addComponent(integerButton))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        numTypePanelLayout.setVerticalGroup(
            numTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(integerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fractionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sortOrderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sort Order"));

        sortOrderButtons.add(descendingButton);
        descendingButton.setText("Descending");
        descendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descendingButtonActionPerformed(evt);
            }
        });

        sortOrderButtons.add(ascendingButton);
        ascendingButton.setSelected(true);
        ascendingButton.setText("Ascending");

        javax.swing.GroupLayout sortOrderPanelLayout = new javax.swing.GroupLayout(sortOrderPanel);
        sortOrderPanel.setLayout(sortOrderPanelLayout);
        sortOrderPanelLayout.setHorizontalGroup(
            sortOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descendingButton)
                    .addComponent(ascendingButton))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        sortOrderPanelLayout.setVerticalGroup(
            sortOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sortOrderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ascendingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descendingButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 244, Short.MAX_VALUE)
                        .addComponent(numTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unsortedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unsortedField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortedField)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(164, 164, 164))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {numTypePanel, sortOrderPanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsortedLabel)
                    .addComponent(unsortedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortedLabel)
                    .addComponent(sortedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descendingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descendingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascendingButton;
    private javax.swing.JRadioButton descendingButton;
    private javax.swing.JRadioButton fractionButton;
    private javax.swing.JRadioButton integerButton;
    private javax.swing.ButtonGroup numTypeButtons;
    private javax.swing.JPanel numTypePanel;
    private javax.swing.ButtonGroup sortOrderButtons;
    private javax.swing.JPanel sortOrderPanel;
    private javax.swing.JTextField sortedField;
    private javax.swing.JLabel sortedLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField unsortedField;
    private javax.swing.JLabel unsortedLabel;
    // End of variables declaration//GEN-END:variables
}
